services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "$PG_ADMIN_PORT:80"
    restart: unless-stopped
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - dev
volumes:
  pgadmin-data: