spring:
  application:
    name: image-service

server:
  port: 8081
  error:
    include-message: always
  servlet:
    context-path: /api/images

minio:
  user: ROOTUSER
  password: PASSWORD
  url: http://host.docker.internal:9000
  bucket-names:
    avatar: avatars-bucket

jwt:
  secret: 3f4b2a7e8f1c3d2a0b5e6c8f2087a4d9c6e5f0bcb16a14f22986f4084e6c6a2d

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs

logging:
  config: classpath:logback-local.xml