{
 "title": "Envelope dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Image service log",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{application=\"image-service\"} |= ``"
    }
   ]
  },
  {
   "title": "Identity service log",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{application=\"identity-service\"} |= ``"
    }
   ]
  },
  {
   "title": "Api gateway log",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{application=\"api-gateway\"} |= ``"
    }
   ]
  }
 ]
}