spring:
  application:
    name: api-gateway

server:
  port: 8090
  error:
    include-message: always
  servlet:
    context-path: /api

hosts:
  identity-service: http://localhost:8080
  image-service: http://localhost:8081

springdoc:
  swagger-ui:
    path: /swagger-ui
    urls:
      - name: Сервис аутентификации и авторизации
        url: /aggregate/identity-service/v1/api-docs
      - name: Сервис изображений
        url: /aggregate/image-service/v1/api-docs
  api-docs:
    path: /api-docs

logging:
  config: classpath:logback-local.xml