spring:
  application:
    name: helper-service
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: ${HELPER_SERVICE_PORT}
  error:
    include-message: always
  servlet:
    context-path: ${HELPER_SERVICE_CONTEXT}

client:
  identity-service:
    url: http://identity-service:${IDENTITY_SERVICE_PORT}
    context-path: ${IDENTITY_SERVICE_CONTEXT}

jwt:
  secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs

logging:
  config: classpath:logback.xml
  loki:
    url: http://loki:${LOKI_PORT}/loki/api/v1/push
  file:
    log-pattern: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"