spring:
  application:
    name: helper-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migration/base

telegram:
  secret-key: ${TG_SECRET_KEY}

server:
  port: ${HELPER_SERVICE_PORT}
  error:
    include-message: always
  servlet:
    context-path: /api/helper

client:
  identity-service:
    url: http://localhost:8080
    context-path: /api/identity

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs

#logging:
#  config: classpath:logback-local.xml