spring:
  application:
    name: helper-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migration/base

telegram:
  secret-key: ${TG_SECRET_KEY}

server:
  port: ${HELPER_SERVICE_PORT}
  error:
    include-message: always
  servlet:
    context-path: ${HELPER_SERVICE_CONTEXT}

client:
  identity-service:
    url: http://identity-service:${IDENTITY_SERVICE_PORT}
    context-path: ${IDENTITY_SERVICE_CONTEXT}

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs

logging:
  config: classpath:logback.xml
  loki:
    url: http://loki:${LOKI_PORT}/loki/api/v1/push
  file:
    log-pattern: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"