spring:
  application:
    name: helper-service
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8082
  error:
    include-message: always
  servlet:
    context-path: /api/helper

client:
  identity-service:
    url: http://localhost:8085
    context-path: /api/identity

logging:
  config: classpath:logback-local.xml